# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0019_auto_20161107_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ('stripe_timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ('stripe_timestamp',)},
        ),
        migrations.AlterField(
            model_name='charge',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer associated with this charge. Null here indicates that this value was never set.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='djstripe.Customer'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='failure_code',
            field=djstripe.fields.StripeCharField(blank=True, choices=[(b'invalid_number', b'Invalid Number'), (b'invalid_expiry_month', b'Invalid Expiry Month'), (b'invalid_expiry_year', b'Invalid Expiry Year'), (b'invalid_cvc', b'Invalid Cvc'), (b'incorrect_number', b'Incorrect Number'), (b'expired_card', b'Expired Card'), (b'incorrect_cvc', b'Incorrect Cvc'), (b'incorrect_zip', b'Incorrect Zip'), (b'card_declined', b'Card Declined'), (b'missing', b'Missing'), (b'processing_error', b'Processing Error'), (b'rate_limit', b'Rate Limit')], help_text=b'Error code explaining reason for charge failure if available.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='failure_message',
            field=djstripe.fields.StripeTextField(blank=True, help_text=b'Message to user further explaining reason for charge failure if available.', null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='shipping',
            field=djstripe.fields.StripeJSONField(blank=True, help_text=b'Shipping information for the charge', null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The source used for this charge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='djstripe.StripeSource'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='statement_descriptor',
            field=djstripe.fields.StripeCharField(blank=True, help_text=b'An arbitrary string to be displayed on your customer\'s credit card statement. The statement description may not include <>"\' characters, and will appear on your customer\'s statement in capital letters. Non-ASCII characters are automatically stripped. While most banks display this information consistently, some may display it incorrectly or not at all.', max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='transfer',
            field=models.ForeignKey(blank=True, help_text='The transfer to the destination account (only applicable if the charge was created using the destination parameter).', null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.Transfer'),
        ),
    ]
